# Generated by Django 3.2.5 on 2021-07-05 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='ISBN')),
                ('nombre_libro', models.CharField(max_length=40, verbose_name='Nombre libro')),
                ('autor', models.CharField(max_length=40, verbose_name='Autor')),
                ('descripcion', models.CharField(max_length=400, verbose_name='Descripción')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
